# Generated by Django 4.0.6 on 2022-11-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
