# Generated by Django 4.0.6 on 2022-11-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_productinbasket_product_productinorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='amount_of_products_in_basket',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
