# Generated by Django 4.0.6 on 2022-11-05 18:33

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_productinbasket_amount_of_products_in_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='name',
            field=models.TextField(blank=True, default=None, null=True, verbose_name=product.models.Product),
        ),
    ]
