# Generated by Django 4.0.6 on 2022-11-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_productinbasket_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='amount_of_products_in_basket',
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='name',
        ),
        migrations.AddField(
            model_name='productinbasket',
            name='price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
